### ISSUE TITLE
Multisite.

### ISSUE THREAD

**Issue by hifall** [Perlkonig/grav-theme-knowledge-base#12]
Does this theme work for multisite?

I have installed it on my server, and verified that it works on single site. However, when I access it in multisite mode, I got:

<img width="635" alt="screen shot 2017-04-15 at 11 26 41 am" src="https://cloud.githubusercontent.com/assets/5734293/25060392/8e6e0412-21ce-11e7-85d6-19706632589e.png">

**Comment by Perlkonig** [comment]
I have no idea. I've done no reading on multisite and am not aware of anything specific I have to do to make a theme multisite ready. That error has to do with the `count-views` plugin and its inability to open your data file. That's unrelated to the theme itself. Make sure your permissions are correct and open an issue on the plugin page (it's my plugin) and we'll see what we can do.

**Comment by hifall** [comment]
Thanks for you suggestion.

I have filed the issue as: https://github.com/Perlkonig/grav-plugin-count-views/issues/2.
