### ISSUE TITLE
Exclude certain categories from knowledge base

### ISSUE THREAD

**Issue by oshyne** [Perlkonig/grav-theme-knowledge-base#14]
Thanks a lot for your wonderful theme that i have easily followed and implemented a knowledge base on a GRAV site.

Please. I need your help in excluding certain categories from the knowledge base. Because, I also have a blog, news and events section on the site. So i want only the knowledge base categories to appear in the knowledge base.

I understand that this is the loops that display the categories of the knowledge base

```
{% for cat in taxonomy.taxonomy['category']|keys|sort|slice(0,maxrows*2) %}
	{% set node = node|merge([cat]) %}
	{% if node|length == 2 %}
		{% set rows = rows|merge([node]) %}
		{% set node = [] %}
	{% endif %}
{% endfor %}
```

I have tried modifying it to this to see if i can filter the categories but still not working

```
{% for cat in taxonomy.findTaxonomy({'category':['Housing','Programme']})|keys|sort|slice(0,maxrows*2) %}
	{% set node = node|merge([cat]) %}
	{% if node|length == 2 %}
		{% set rows = rows|merge([node]) %}
		{% set node = [] %}
	{% endif %}
{% endfor %}
```

Thanks for your kind help.

**Comment by Perlkonig** [comment]
I'll add a `blacklist` field to the settings. Give me a little time.

**Comment by Perlkonig** [comment]
See new release.

**Comment by oshyne** [comment]
Thanks so much.
