### ISSUE TITLE
Category missing from list.

### ISSUE THREAD

**Issue by hifall** [Perlkonig/grav-theme-knowledge-base#16]
The last category is missing from list, when the number of categories is odd.

For example, say you have 5 categories, and only the first 4 are displayed, the 5th is missing. If you create a new category to make the total 6, all are displayed.

**Comment by Perlkonig** [comment]
Are you sure you're using the latest version. That should have already been fixed.

**Comment by hifall** [comment]
I downloaded the skeleton from getgrav.org, then updated using gpm.

**Comment by hifall** [comment]
The issue does seem gone with the latest. Sorry about the false warning!

**Comment by Perlkonig** [comment]
No worries. The skeleton is out of date. Glad you figured it out.
