### ISSUE TITLE
How to exclude search bar and sidebar from a specific page?

### ISSUE THREAD

**Issue by anto** [Perlkonig/grav-theme-knowledge-base#19]
I would like to exclude the search bar and sidebar from some specific pages, e.g. http://<my domain/about. How would I be able to do that?

Is customising this theme using Theme Inheritance method the only way to achieve that?

Thanks a lot in advance

**Comment by Perlkonig** [comment]
That's the best way. That way you can download any updates without losing your customizations. You'd just have to override `partials/base.html.twig`, which shouldn't change much over time. Let me know if you run into trouble.
