### ISSUE TITLE
Error 404 on accessing Categories

### ISSUE THREAD

**Issue by anto** [Perlkonig/grav-theme-knowledge-base#20]
Hello Aaron,

I am not sure if this is an issue on Knowledge Base theme, or generic configuration issue on my Grav CMS.

I have started to put content on my web site. So far only 1 topic per categories. And I have only 3 categories so far. When I click on any categories, e.g. Grav CMS, I got error 404. The URL of the missing content is for instance `http://<my domain>/taxonomy?name=category&val=Grav%20CMS`.

So unlike on the demo page `https://www.perlkonig.com/knowledge-base/` where I can access any categories, e.g. Topic 1, I get error 404 on my web site.

What could be the cause of this issue? Or is it because I missed installing any other plugins a part from the required ones? If so, which one please?

Thanks a lot in advance for your help.

Kind regards,

Anto

**Comment by Perlkonig** [comment]
I can't tell from this explanation alone. Did you install all [the required plugins](https://github.com/Perlkonig/grav-skeleton-knowledge-base/blob/master/.dependencies)? If you want you can send me a zip of your `/user` folder and I can see if I can replicate the problem.

**Comment by Cyzerx** [comment]
I have exact same issue, can you tell me how you fixed it ?

**Comment by Perlkonig** [comment]
If you send me a zip of your user folder, I can try to replicate the problem.

**Comment by Cyzerx** [comment]
How I can send it to you? Im pretty new in github

**Comment by Cyzerx** [comment]
[user.zip](https://github.com/Perlkonig/grav-theme-knowledge-base/files/1483343/user.zip)

**Comment by Cyzerx** [comment]
Where ?

**Comment by Perlkonig** [comment]
You deleted the `user/pages/taxonomy` folder. Don't do that 😄
