### ISSUE TITLE
Navigation menu isnt responsive

### ISSUE THREAD

**Issue by sebasvisser** [Perlkonig/grav-theme-knowledge-base#23]
See https://cl.ly/rNPm

The menu items don't go to the next line when the width is smaller. The Website Title does however..

**Comment by Perlkonig** [comment]
I can't seem to replicate. I'm going to [the demo site](https://www.perlkonig.com/knowledge-base/) and resizing the browser window using developer tools and everything appears to be wrapping correctly. It works on my phone as well. Could it be an issue with your emulator? Or have you altered the CSS?

**Comment by Perlkonig** [comment]
![2018-05-04 16_33_23-responsive layouts from https___www perlkonig com_knowledge-base_](https://user-images.githubusercontent.com/4873640/39655808-00d69848-4fb9-11e8-8e9e-3143b7134a09.png)

**Comment by Perlkonig** [comment]
If you want you can send me your user folder and I'll see what I can see.

**Comment by sebasvisser** [comment]
Hmmz, yeah thats weird, the demo works perfectly.
I did change some stuff left and right..but don't think I changed anything to break that...

here is my user folder: (I deleted most of the articles since they contain sensitive data)
https://www.dropbox.com/sh/ua3r290cc6bdaum/AABm363Y-WE__7keqogXor4La?dl=0

**Comment by Perlkonig** [comment]
Test site up and seems to be working as expected: https://www.perlkonig.com/scratch/knowledge-base/nl.

![2018-05-04 21_04_56-responsive layouts from https___www perlkonig com_scratch_knowledge-base_nl](https://user-images.githubusercontent.com/4873640/39659135-f2177978-4fde-11e8-87c1-d2bdefa40841.png)

**Comment by sebasvisser** [comment]
hmmz..this is weird..I think it's my computer!!

See screengrab: https://cl.ly/rPFM

So that means this issue should be closed, I'll sort my little Dell out, if I can find out why the hell it's doing this..

**Comment by Perlkonig** [comment]
Well HTML rendering is not an exact science. I hope you can get it figured out. I'll leave the site up at least for today.
