### ISSUE TITLE
relatedpages doesn't work

### ISSUE THREAD

**Issue by ghost** [Perlkonig/grav-theme-knowledge-base#26]
For some reason that I couldn't figure out yet the related pages are not showing up. But there a quiet a few pages that contain the same tags and fit into the same category.

Did I configure the plugin wrong? Is there something missing in the theme that I should watch out for?

**Comment by Perlkonig** [comment]
There is no reason I'm aware of why the theme would interfere with the plugin working. I suggest rereading the plugin's docs and maybe filing an issue there. If there's some reason to believe the theme is the problem, then come on back.
