### ISSUE TITLE
How should i add two front modules in your theme?

### ISSUE THREAD

**Issue by Maclaon** [Perlkonig/grav-theme-knowledge-base#27]
i would like to add two `front` type pages in my post? but it shows the same content when i have posted in a article？

**Comment by Perlkonig** [comment]
Why would you want two different `front` pages? You create multiples just like you created the first. You simply create a `front.md` file somewhere. It's a main template type. Or am I misunderstanding you?

**Comment by Perlkonig** [comment]
Feel free to reopen if you have more information.
