### ISSUE TITLE
Articles are not showing up on homepage

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#3]
@Perlkonig Hi, any idea why I'm getting empty frontpage, please? Thanks.

![screen shot 2017-02-22 at 11 49 30](https://cloud.githubusercontent.com/assets/1004491/23208371/068a6c86-f8f5-11e6-9b8a-d7dc67936dff.png)

**Comment by Perlkonig** [comment]
Afraid not. Can you zip up your user folder and send it to me? I'll try to replicate.

**Comment by rbukovansky** [comment]
@Perlkonig Here it comes... 
[rbukovansky_user.zip](https://github.com/Perlkonig/grav-theme-knowledge-base/files/793355/rbukovansky_user.zip)

Thanks!

**Comment by rbukovansky** [comment]
And thanks.

**Comment by rbukovansky** [comment]
@Perlkonig Hi, got any chance to check it out, please? Thanks.

**Comment by Perlkonig** [comment]
I haven't, I'm sorry. I will try to squeeze it in today, but it may have to wait until my day off tomorrow.

**Comment by rbukovansky** [comment]
@Perlkonig That's OK, no rush...

**Comment by Perlkonig** [comment]
When I run it I get a "page not found" on the home page. The specific authors and articles are working, but the sidebar looks like your screen capture. I've poked around a little bit, but can't get it to work. I'll take another look tomorrow. I don't know enough about Grav's international support to know if that's part of the problem.

**Comment by Perlkonig** [comment]
Part of the problem is `params:articleroot` not being properly set in `user/themes/knowledge-base/knowledge-base.yaml`. Only part of the problem, though.

**Comment by Perlkonig** [comment]
I should add that you should modify that config file [as described in the docs](https://learn.getgrav.org/themes/theme-configuration) (i.e., copying to `user/config` and editing there).

**Comment by rbukovansky** [comment]
I have tried to set `params:articleroot` back to `/home` with renaming `01.Domů` folder back to `01.home` and setting value of `Title` in header of `front.md` in `01.Home` folder to `Home`, but no luck either. Still empty homepage... :cry:

**Comment by rbukovansky** [comment]
@Perlkonig Any chance you've time to look at it, please? Thanks.

**Comment by Perlkonig** [comment]
I'm sorry, but I haven't. My life is, shall we say, chaotic at the moment. [The theme works generally](https://perlkonig.com/knowledge-base), so I'd recommend starting with a fresh install and slowly replicating your changes until you find the point at which it breaks. I'm leaving the issue open, and if I can make some time, I will, but I can't make any promises as to timelines. There are so many demands on my attention this month.

**Comment by rbukovansky** [comment]
OK. I think I have figured out this issue.
It seems to me, if you have just one topic specified in your pages files, than it fails to show that Article Categories part of homepage correctly.

**Comment by Perlkonig** [comment]
It's true that the list of topics doesn't display as it should, but it doesn't generate the 404 that was happening to you. I'll figure out why a single topic isn't appearing. That said, a knowledge base with only one topic isn't much of a knowledge base 😄 

Thanks!

**Comment by rbukovansky** [comment]
Well, I beg to differ with that statement, 'cause I can think about few situations, where it can be suitable...

Anyway, please take care of that. I'm closing this issue.

**Comment by Perlkonig** [comment]
Sorry. Didn't mean to offend. I will take a look. All the best.

**Comment by rbukovansky** [comment]
No offence taken! Aaron, please, no need to apologize. I'm really glad you created this theme for Grav.

I'm just pointing to the situation there might be i.e. company with just one small product with need of simple KB with just few articles regarding their product, hence that one topic KB. It can happen and I believe you don't want to disappoint your users. :wink:
