### ISSUE TITLE
Last articles in Sidebar doesn't work when using subdirectories

### ISSUE THREAD

**Issue by ftertre** [Perlkonig/grav-theme-knowledge-base#32]
When we use subdirectories in the HOME folder, the component _Last articles_ of the sidebar doesn't work well. It tries to display the parents directories as an article, but not the articles in the subdirectories.

I see in the code that this is related to that line.
`{% set articles = page.find(homeroute).children.order('date', 'desc') %}`

But I don't have enough skills with twig & co to be able to propose a fully working PR.

**Comment by Perlkonig** [comment]
I'll see what i can do.

**Comment by Perlkonig** [comment]
Salut! Can you clarify how your pages are set up so I can accurately replicate and correct the code? I assume you mean that in your pages folder you have a structure like the following:

```yaml
- 01.HOME
  - folder1
    - article1
      - item.md
    - article2
      - item.md
  - folder2
    - article3
      - item.md
    - article4
      - item.md
```

This is what I'm going to test with and see what I can do. If there's more to your question, please let me know. Merci!

**Comment by Perlkonig** [comment]
Problem fixed. New release forthcoming.
