### ISSUE TITLE
How to use Category page teplate?

### ISSUE THREAD

**Issue by mymurkas** [Perlkonig/grav-theme-knowledge-base#35]
Firstly, thanks for a great theme!
But I wonder how to use the new cetegory page template. You write "Categories can now have landing pages" but how do I get that to work?

**Comment by Perlkonig** [comment]
See the skeleton repository for sample pages. That's the simplest answer 😊

https://github.com/Perlkonig/grav-skeleton-knowledge-base

**Comment by mymurkas** [comment]
Great! I forgot about the skeleton. Thank you!
