### ISSUE TITLE
Req: up-to-date skeleton

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-theme-knowledge-base#36]
I (still) love this theme and have it in use.
I've had quite some trouble updating it from 1.5 to GRAV 1.6.26.
Eventually I've got it to work, and it is still works like a charm!

It would be great (for new users) if the skeleton could be updated to the latest GRAV 1.6.x version

**Comment by Perlkonig** [comment]
Sorry for the neglect. I just don't keep up with Grav releases. I have a bunch of plugins I need to test too. I will make some time for this shortly (vacation coming).

**Comment by Perlkonig** [comment]
Turns out the plugins were fine. New skeleton released. Glad you find the theme useful.
