### ISSUE TITLE
Req: disable display of page.media.images at end of content

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-theme-knowledge-base#37]
Is there a compelling reason to display (again) all page.media.images at the end of a page?

item.html.twig:

```
<section class="content">
   {{ page.content }}
   <p></p>
   {% for image in page.media.images %}
      {{ image.cropResize(700, 400).html("title", "alt", "itemscreenshot") }}
   {% endfor %}
</section>

```
Is it possible to define a frontmatter-variable to suppress this? 
e.g. show_pagemedia

```
{% if page.header.show_pagemedia %}
   {% for image in page.media.images %}
      {{ image.cropResize(700, 400).html("title", "alt", "itemscreenshot") }}
   {% endfor %}
{% endif %}

```

**Comment by Perlkonig** [comment]
No *compelling* reason. The intended use case was that the media wouldn't be directly referenced in the content. But options are always good. To not break existing sites, I would prefer we did the inverse and added a `page.header.hide_mediasummary` to suppress it per page. Would that work for you?

**Comment by awrog** [comment]
Sure that would work!
I was trying to adhere to what is already there (show_sidebar, show_breadcrumbs, show_pagination), but on the other hand, there's also hide_page_title.
We should definately not break things.

**Comment by Perlkonig** [comment]
New version released. Please test it out and let me know if it works for you. If so, I'll update the skeleton.

**Comment by awrog** [comment]
Works like a charm!

(I love it when you don't have to check for missing variables of null values! ;-) )

**Comment by Perlkonig** [comment]
Glad to hear it. Thanks. New skeleton forthcoming.
