### ISSUE TITLE
[FeatReq] Options to show parts of pages

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#4]
@Perlkonig Do you think it would be possible to make this theme more "optional", meaning On/Off switches which will show or hide parts of pages? I.e.:

- [ ] Show Popular articles
- [ ] Show Latest articles
- [ ] Show Date of article
- [ ] Show Author of article

etc.?

**Comment by Perlkonig** [comment]
I've added config values to show/hide sidebar modules and article header components. A new release should be made this weekend (I hope). But I should note that I do not use the Admin module and don't have the time to learn it. These config values need to be set manually in `knowledge-base.yaml` with a text editor, as described [in the docs](https://learn.getgrav.org/themes/theme-configuration). 

If anyone out there is familiar with coding themes for the Admin module, I would warmly welcome pull requests.

**Comment by Perlkonig** [comment]
v1.2.0 released.

**Comment by rbukovansky** [comment]
I guess I will work on that Admin part for this theme.

Thanks for the changes!
