### ISSUE TITLE
[FeatReq] Options for style of listings articles on homepage

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#5]
I would like to be able to tell what to show on homepage, meaning how to list articles and which on homepage. I.e.:

Combobox with this options

- Last 5 articles per category (current behaviour)
- Last 5 articles of the whole site
- Selected 5 articles with 5 input field for article links
   - /article01
   - /article05
   - /article02
   - /article04
   - /article03

Would it be possible?

**Comment by Perlkonig** [comment]
* You can certainly change the number of articles per category that are displayed. 
* The theme is designed for showing articles by category. Showing latest articles is done in the sidebar. 
* This is much more difficult. While I like the idea of "pinning" articles, it requires more work than I have time to commit right now. For now the order is whatever `findTaxonomy` returns [(docs)](https://learn.getgrav.org/content/taxonomy). I'll add this to the wishlist, but it won't happen anytime soon, I'm afraid.

Thanks for submitting this, though!

**Comment by rbukovansky** [comment]
That's OK. It was just an idea.
