### ISSUE TITLE
Comments in this theme

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#8]
I'm trying to decipher why this is part of template `item.html.twig`:

```html
<section class="comments">
     <h2>{{ 'COMMENTS'|t }}</h2>
</section>
```

Is there any reason for it? Is there any plugin this is dependable on? If so, could it please show it only when that plugin is available and enabled?

Thanks.

**Comment by Perlkonig** [comment]
It's just a placeholder. There are numerous different approaches/plugins you could use to accept comments, and you'd have to edit the template accordingly.

**Comment by rbukovansky** [comment]
I see... OK.

Well, we need that inheritence get working then... :)
