### ISSUE TITLE
Theme inheritence

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#9]
I'm trying to create inherited theme, but as I have submitted here https://github.com/getgrav/grav/issues/1353 it doesn't seem to be working.

Any idea what could be wrong? Thank you.

**Comment by Perlkonig** [comment]
No specific reason, no. I'll try to do it myself sometime today, if I can, and see what happens.

**Comment by rbukovansky** [comment]
Thanks.

**Comment by Perlkonig** [comment]
Inheritance works fine until the PHP stage for me, too. I'm sure it has something to do with the hyphenated file name. I see this mentioned [in the forum](https://getgrav.org/forum#!/theme-development:theme-inheritance-problem_1), but no solution is given. I didn't think I could simply rename my php file `knowledgebase.php` and it still work. We'll see what the Grav folks say.

**Comment by rbukovansky** [comment]
Well, I have did that renaming as I have mentioned in getgrav/grav#1353  and it works...

**Comment by Perlkonig** [comment]
Moving conversation there, then.
